### ISSUE TITLE
`configStore` variable is not found

### ISSUE THREAD

**Issue by tdoan2010** [themeselection/materio-vuetify-nuxtjs-admin-template-free#1]
### Steps to reproduce

1. Git clone the project.
2. Open the `typescript-version`.
3. Run `pnpm install`.
4. In the `app.vue` file, WebStorm complains that the variable `configStore` was not defined anywhere.

### What is expected?

`configStore` variable should be defined somewhere.

### What is actually happening?

`configStore` is not defined anywhere.

### Additional data

NodeJS Version: 21.6.1
Package manager: pnpm
Browser name & version: Google Chrome version 120.0.6099.234
System: MacOS

**Comment by DeepKumbhare85** [comment]
Hello @tdoan2010, 

Thanks for getting in touch with us. 

We've cloned the repository and installed all the dependencies, but we're unable to replicate the issue. We couldn't find any instance where `configStore` is not defined in our template. I kindly request you to reinstall the template afresh. Please inform me if you continue to encounter the issue.

**Comment by zmaten** [comment]
I am able to reproduce the issue. Although the application runs correctly, VS Code still underlines the `configStore`and lists the issue in `PROBLEMS` tab with the message mentioned in the OP.
![image](https://github.com/user-attachments/assets/85612c7f-fa3d-4491-b269-d296567a647c)
